import { StyleSheet } from 'react-native';
import { FONTS, RADIUS, SPACING } from '../../theme/colors';
import { BG, ACCENT, CARD, BLUE, BUBBLE_BG, BUBBLE_BORDER } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  backBtn:       { width: 32, alignItems: 'center', justifyContent: 'center' },
  backText:      { fontSize: 22, color: 'rgba(255,255,255,0.6)', fontWeight: '600' },
  progressTrack: { flex: 1, height: 5, borderRadius: RADIUS.pill, backgroundColor: 'rgba(255,255,255,0.1)', overflow: 'hidden', justifyContent: 'center' },
  progressFill:  { ...StyleSheet.absoluteFillObject, height: '100%' },

  centerFull: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: SPACING.xl },
  stepWrap:   { flex: 1, paddingHorizontal: SPACING.lg },

  mascotRow: { flexDirection: 'row', alignItems: 'flex-end', gap: SPACING.md, marginBottom: SPACING.lg, paddingTop: SPACING.sm },
  bubbleSide: {
    flex: 1,
    backgroundColor: CARD,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  bubbleSideText: { ...FONTS.body, color: '#fff', lineHeight: 24 },

  optionList:    { flex: 1 },
  optionTouchable: { marginBottom: SPACING.sm, borderRadius: RADIUS.md, overflow: 'hidden' },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CARD,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: SPACING.md,
    paddingVertical: 16,
    gap: SPACING.sm,
  },
  optionRowSelected:   { borderColor: ACCENT },
  optionLabel:         { ...FONTS.body, color: '#fff', fontWeight: '600', flex: 1 },
  optionLabelSelected: { color: ACCENT },
  optionTag:           { ...FONTS.sm, color: 'rgba(255,255,255,0.5)', fontWeight: '600' },
  optionTagSelected:   { color: ACCENT },

  checkDot: {
    width: 24, height: 24, borderRadius: 12,
    borderWidth: 2, borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  checkDotSelected: { backgroundColor: BLUE, borderColor: BLUE },
  checkDotText:     { color: '#fff', fontSize: 13, fontWeight: '900' },

  levelBadge:     { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.12)' },
  levelBadgeText: { fontSize: 9, fontWeight: '800', color: 'rgba(255,255,255,0.7)', letterSpacing: 0.8 },

  loadingLabel:    { ...FONTS.xs, color: 'rgba(255,255,255,0.35)', letterSpacing: 1.5, marginTop: SPACING.lg, marginBottom: SPACING.md },
  loadingBarTrack: { width: '100%', height: 8, borderRadius: RADIUS.pill, backgroundColor: 'rgba(255,255,255,0.1)', overflow: 'hidden', marginBottom: SPACING.lg },
  loadingBarFill:  { height: '100%', borderRadius: RADIUS.pill, backgroundColor: ACCENT },
  loadingText:     { ...FONTS.body, color: 'rgba(255,255,255,0.7)', textAlign: 'center', lineHeight: 28 },

  sellScroll: { paddingHorizontal: SPACING.lg, paddingTop: 32, paddingBottom: SPACING.xl },
  sellTitle:  { fontSize: 32, fontWeight: '900', color: '#FFFFFF', marginBottom: 12, lineHeight: 42 },
  sellSub:    { fontSize: 16, color: 'rgba(255,255,255,0.45)', lineHeight: 24, marginBottom: 28 },
  catalogScroll: { paddingLeft: 24, paddingRight: 8, gap: 10, paddingVertical: 4 },
  catalogCard: {
    width: 100, height: 110,
    backgroundColor: '#1C1C1E', borderRadius: 16,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, gap: 8,
  },
  catalogIcon:  { fontSize: 28 },
  catalogTitle: { fontSize: 13, fontWeight: '800', color: '#F0F4FF', textAlign: 'center' },
  catalogSub:   { fontSize: 10, color: 'rgba(255,255,255,0.35)', textAlign: 'center' },
  statsChocRow: {
    flexDirection: 'row',
    backgroundColor: CARD,
    borderRadius: 18,
    paddingVertical: 22,
    paddingHorizontal: 8,
    marginBottom: 32,
    alignItems: 'center',
  },
  statsChocItem:  { flex: 1, alignItems: 'center' },
  statsChocNum:   { fontSize: 28, fontWeight: '900', color: '#FFFFFF', marginBottom: 4 },
  statsChocLabel: { fontSize: 12, color: 'rgba(255,255,255,0.4)', fontWeight: '500' },
  statsChocSep:   { width: 1, height: 38, backgroundColor: 'rgba(255,255,255,0.1)' },

  featureRow: {
    flexDirection: 'row', alignItems: 'center', gap: 16,
    paddingVertical: 15,
    borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  featureIcon: {
    width: 48, height: 48, borderRadius: 12,
    backgroundColor: CARD, alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
  },
  featureText:  { flex: 1 },
  featureTitle: { fontSize: 16, fontWeight: '800', color: '#fff', marginBottom: 3 },
  featureSub:   { fontSize: 13, color: 'rgba(255,255,255,0.45)', lineHeight: 18 },

  profileScroll:    { paddingHorizontal: SPACING.lg, paddingTop: SPACING.md, paddingBottom: 48 },
  sectionBadgeRow:  { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.lg },
  sectionBadge:     { ...FONTS.xs, color: 'rgba(255,255,255,0.4)', fontWeight: '800', letterSpacing: 1.2 },
  sectionBadgeStep: { ...FONTS.xs, color: 'rgba(255,255,255,0.4)', fontWeight: '700' },
  profileTitle:    { fontSize: 28, fontWeight: '900', color: '#FFFFFF', marginBottom: SPACING.sm, lineHeight: 36 },
  profileSubtitle: { ...FONTS.sm, color: 'rgba(255,255,255,0.4)', lineHeight: 20, marginBottom: SPACING.xxl ?? 40 },
  fieldGroup: { marginBottom: 36 },
  fieldLabel: {
    fontSize: 10, fontWeight: '800', color: 'rgba(255,255,255,0.4)',
    letterSpacing: 1.5, marginBottom: 10,
  },
  fieldInput: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(255,255,255,0.2)',
    color: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 0,
    fontSize: 20,
    fontWeight: '600',
  },
  genderRow:            { flexDirection: 'row', gap: 12, marginTop: 16 },
  genderBtn:            { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 12, borderRadius: RADIUS.md, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.12)', backgroundColor: 'rgba(255,255,255,0.04)' },
  genderBtnSelected:    { borderColor: '#1A4AFF', backgroundColor: 'rgba(26,74,255,0.15)' },
  genderSymbol:         { fontSize: 20, color: 'rgba(255,255,255,0.4)' },
  genderSymbolSelected: { color: '#1A4AFF' },
  genderLabel:          { fontSize: 14, fontWeight: '700', color: 'rgba(255,255,255,0.4)' },
  genderLabelSelected:  { color: '#A0B8FF' },

  fieldMatricule: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A4AFF',
    letterSpacing: 2,
    paddingVertical: 12,
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(26,74,255,0.3)',
  },

  ordreCard: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: '#1A4AFF',
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    marginBottom: SPACING.xl,
    marginTop: SPACING.lg,
  },
  ordreHeader: {
    backgroundColor: '#002395',
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ordreHeaderLabel: { fontSize: 10, fontWeight: '900', color: '#FFFFFF', letterSpacing: 1.5 },
  ordreHeaderRef:   { fontSize: 9,  fontWeight: '600', color: 'rgba(255,255,255,0.5)', letterSpacing: 0.8 },
  ordreBody:        { padding: SPACING.md, backgroundColor: 'rgba(26,74,255,0.06)' },
  ordreObjet:       { fontSize: 12, fontWeight: '800', color: '#A0B8FF', letterSpacing: 0.5, marginBottom: SPACING.md, lineHeight: 18 },
  ordreText:        { ...FONTS.body, color: 'rgba(255,255,255,0.7)', lineHeight: 24, marginBottom: SPACING.lg },
  ordreSignature:   { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)', paddingTop: SPACING.sm, flexDirection: 'row', justifyContent: 'space-between' },
  ordreSignatureText: { fontSize: 10, color: 'rgba(255,255,255,0.3)', fontWeight: '600' },
  ordreSignatureDate: { fontSize: 10, color: 'rgba(255,255,255,0.3)' },

  notifYesBtn:     { backgroundColor: '#002395', borderRadius: RADIUS.pill, paddingVertical: 18, alignItems: 'center', width: '100%', marginBottom: SPACING.sm, borderWidth: 1, borderColor: '#1A4AFF' },
  notifYesBtnText: { fontSize: 16, fontWeight: '900', color: '#FFFFFF', letterSpacing: 1 },
  notifNoBtn:      { paddingVertical: 14, alignItems: 'center', width: '100%' },
  notifNoBtnText:  { ...FONTS.body, color: 'rgba(255,255,255,0.25)', fontWeight: '600' },

  footer:          { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.xl, gap: SPACING.sm },
  cta:             { borderRadius: RADIUS.pill, paddingVertical: 18, alignItems: 'center' },
  ctaDisabled:     { backgroundColor: '#1C1C1E', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  ctaText:         { fontSize: 16, fontWeight: '900', color: '#FFFFFF', letterSpacing: 1 },
  ctaTextDisabled: { color: 'rgba(255,255,255,0.3)' },
});

export const chatStyles = StyleSheet.create({
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.xl,
  },
  centerBubble: {
    backgroundColor: BUBBLE_BG,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderWidth: 2,
    borderColor: 'rgba(68, 136, 255, 0.6)',
    width: '100%',
    height: 130,
    justifyContent: 'center',
    marginTop: SPACING.xl,
  },
  centerBubbleText: { fontSize: 17, color: '#FFFFFF', lineHeight: 26, textAlign: 'center', fontWeight: '400' },

  sideContainer: { flex: 1, paddingHorizontal: SPACING.lg, paddingTop: SPACING.xl },
  sideRow:       { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.md },
  sideBubble: {
    flex: 1,
    backgroundColor: BUBBLE_BG,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderWidth: 2,
    borderColor: 'rgba(68, 136, 255, 0.6)',
  },
  sideBubbleText: { fontSize: 17, color: '#FFFFFF', lineHeight: 26, fontWeight: '400' },
});
